name: forest_island
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "0.5.1"
  firebase_auth: "^0.18.2"
  http: ^0.12.2
  html: ^0.14.0+3
  crypto: ^2.0.6
  flutter_rating_bar: ^3.2.0
  get:
  getwidget: ^1.1.0
  url_launcher: ^5.7.10
  camera: ^0.5.8+17 
  barcode_scan: ^3.0.1
  introduction_screen: ^1.0.9
  shared_preferences: ^0.5.12+4
  rxdart: 0.22.2
  yandex_mapkit: ^0.5.0
  network_image_to_byte: ^0.0.1
  geolocator: ^5.0.0
  flutter_bloc: ^6.1.1
  modal_bottom_sheet: ^1.0.0+1
  flutter_stories:
  dashed_circle: ^0.0.1
  flutter_share: ^1.0.5
  flutter_switch: ^0.2.0
  page_transition: "^1.1.5"
  flutter_masked_text: ^0.8.0
  dio: ^3.0.10
  auto_size_text: ^2.1.0
  cached_network_image: ^2.0.0
  sms_autofill: ^1.3.1
  searchable_dropdown: ^1.1.3
  flutter_animation_set: ^0.0.3
  scroll_app_bar: ^1.0.3
  flutter_svg: ^0.19.0


  provider: ^4.3.2+1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/xpage_logo_black.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Raster.jpg
    - assets/images/banner_1.jpg
    - assets/images/list_icon0.png
    - assets/images/list_icon1.png
    - assets/images/list_icon2.png
    - assets/images/list_icon3.png
    - assets/images/list_icon4.png
    - assets/images/list_icon5.png
    - assets/images/xpage_logo_light.jpg
    - assets/images/xpage_logo_black.png
    - assets/images/introduction1.png
    - assets/images/introduction2.png
    - assets/images/introduction3.png
    - assets/images/introduction4.png
    - assets/images/introduction5.png
    - assets/images/introduction6.png
    - assets/images/ravis-marker.png
    - assets/images/user-location.png
    - assets/images/RavStories1.png
    - assets/images/RavStories2.png
    - assets/images/RavStories3.png
    - assets/images/greetings_logo.png
    - assets/images/rav-text-logo.png
    - assets/images/white_animation.gif
    - assets/images/empty_favorites.svg
    - assets/images/empty_order-history.svg
    - assets/images/empty_cart.svg
    - assets/images/empty_search.svg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
          weight: 100
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 500
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
        - asset: assets/fonts/FiraSans-Light.ttf
          weight: 100
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 500
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 500
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
